# Generated by Django 5.1.3 on 2025-01-19 04:27

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorsession',
            options={'ordering': ['-scheduled_time']},
        ),
        migrations.AlterField(
            model_name='call',
            name='room_id',
            field=models.CharField(default=app.models.generate_room_id, max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='mentorsession',
            unique_together={('mentor', 'scheduled_time')},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
