# Generated by Django 5.1.3 on 2025-01-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='school',
        ),
        migrations.AddField(
            model_name='course',
            name='schools',
            field=models.ManyToManyField(related_name='courses', to='app.school'),
        ),
    ]
