# Generated by Django 5.1.3 on 2025-01-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='content',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
