# Generated by Django 5.1.3 on 2025-01-18 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_course_school_course_schools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to='app.course'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to='app.school'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_profile', to='app.user'),
        ),
        migrations.AlterField(
            model_name='mentorrating',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='app.mentee'),
        ),
        migrations.AlterField(
            model_name='mentorrating',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.mentorsession'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='app.user'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='app.course'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to='app.user'),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app.mentee'),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app.mentorsession'),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('expertise', models.ManyToManyField(related_name='mentors', to='app.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to='app.user')),
            ],
        ),
        migrations.AlterField(
            model_name='mentorrating',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='app.mentor'),
        ),
        migrations.AlterField(
            model_name='mentorsession',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.mentor'),
        ),
    ]
